@echo off
echo Iniciando servidor Next.js...
echo Limpiando cache...
if exist .next rmdir /s /q .next
echo Iniciando servidor...
set NODE_OPTIONS=--max-old-space-size=4096
npx next dev --port 3000
pause
